### ISSUE TITLE
Last issues for 0.1

### ISSUE THREAD

**Issue by gnuheidix** [gnuheidix/dicomux#12]
Imho we should add some more information to the about information box. Especially the used external libraries with their licenses are important. Maybe a link to the homepage of the libraries would be nice. These additions can be done by rewriting the HTML information in the language files.

Do we want to add the user manual to Dicomux? In the main menu we could add the item Help => User manual. This could be the same mechanism as in the about tab. Language file with HTML code, JEditorPane, Pictures are supported,... I could create this User manual tab within 15 minutes but adding the content would be much work. Is there a tool which can generate HTML from Latex?

**Comment by nostroh** [comment]
I agree we should mention the libraries and have a link to the websites on the about tab.
I see the user manual as a nice-to-have. This would be a working package for the next release. There are comand line tools like latex2html so this should not be a problem once we have the user manual in latex.

**Comment by gnuheidix** [comment]
I'm now implementing the new about page.

**Comment by gnuheidix** [comment]
done
