### ISSUE TITLE
RAWPlugin

### ISSUE THREAD

**Issue by gnuheidix** [gnuheidix/dicomux#6]
The RawPlugin loads all DicomElements recursively. It is possible that this method runs until the JVM stops it on the hard way. That's dangerous. Some limits have to be set in order to avoid bad things to happen.

**Comment by nostroh** [comment]
To make it short: noo its not ;-)
The plugin stops if there are no more DicomElements or DicomObject inside the opend file or have I missed something?

**Comment by gnuheidix** [comment]
Just imagine somebody wants to do something bad. http://blog.fefe.de/?ts=b5250fa9

**Comment by gnuheidix** [comment]
is the new format of the DicomElements ok?

**Comment by gnuheidix** [comment]
everything seems ok
