### ISSUE TITLE
WaveformPlugin

### ISSUE THREAD

**Issue by gnuheidix** [gnuheidix/dicomux#7]
The waveform plug-in doesn't work for all available files. There seems to be an ArrayOutOfBoundsException.

**Comment by nostroh** [comment]
Which file did you try?

**Comment by nostroh** [comment]
The array had a fixed size, changed that so the size depends on the number of channels

**Comment by gnuheidix** [comment]
Position doesn't work with 3 lead (General 3 leads --- *-1)

**Comment by nostroh** [comment]
Fixed, now showing only 3 leads when a file is opened
